# -*- coding: utf-8 -*-
"""Grafico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcJGwgAa6W1QHlF_PNMgapEv9XSxQ3_2
"""

import streamlit as st

st.set_page_config(page_title="Diagnóstico", layout="wide")

st.title("🔍 Diagnóstico — Streamlit rodando")
st.write("Se você está vendo isto, o frontend está OK.")

# Um teste supersimples que SEMPRE renderiza
st.line_chart({"serie":[1, 3, 2, 4]})
st.success("✅ Renderizou. Agora troque este arquivo pelo dashboard.")