# -*- coding: utf-8 -*-
"""Grafico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcJGwgAa6W1QHlF_PNMgapEv9XSxQ3_2
"""

import streamlit as st
import pandas as pd
import altair as alt

st.set_page_config(page_title="Teste Streamlit", layout="wide")
st.title("✅ Deploy funcionando")

dados = pd.DataFrame({
    "Sexo": ["Masculino","Masculino","Feminino","Feminino"],
    "Idade": [25, 35, 29, 42],
    "Salario": [2500, 9000, 3695.36, 23654.48]
})

st.write("Tabela de exemplo", dados)

chart = (alt.Chart(dados)
         .mark_line(point=True)
         .encode(x="Idade:Q", y="Salario:Q", color="Sexo:N"))
st.altair_chart(chart, use_container_width=True)